### ISSUE TITLE
CDATA section ignored in KML description

### ISSUE THREAD

**Issue by robertico01** [makinacorpus/Leaflet.FileLayer#17]
When I load a KML file the KML description is ignored when it's inside a CDATA section.

This works just fine,
```
      <description>
           Here is some text
      </description>
```

but not this one;
```
      <description>
        <![CDATA[
             Here is some text
        ]]>
      </description>
```

It seems an old issue in togeojson.js and should be fixed https://github.com/mapbox/togeojson/issues/42
Using the latest togeojson.js file doesn't solved my problem.

Is this a leaflet.filelayer issue or togeojson.js ?

Regards,

Robertico

**Comment by SBats** [comment]
I close this issue. If someone has still problems with it please reopen !
