### ISSUE TITLE
Leaflet.FileLayer (demo) doesn't work for geojson files

### ISSUE THREAD

**Issue by kkdd** [makinacorpus/Leaflet.FileLayer#18]
Hello,
I have realized that the demo, http://makinacorpus.github.io/Leaflet.FileLayer/index.html, doesn't work for geojson files, but for kml files.
ps. I would appreciate it if you could put some sample files in the Leaflet.FileLayer directory.

**Comment by enguerran** [comment]
#32 was merged, I close this issue.
