### ISSUE TITLE
How to remove the FileLAyer control on map?

### ISSUE THREAD

**Issue by mahmoudmy** [makinacorpus/Leaflet.FileLayer#23]
I tried to remove the created `fileLayer` control by using `fileLayer.removeFrom(map)`, but it doesn't work! Any idea?

**Comment by leplatrem** [comment]
You are right, it looks like the remove function were not implemented :) 

Feel free to open a pull-request to add those! It should not be extremely complex, but don't hesitate to submit a draft so that we can help you

**Comment by SBats** [comment]
Hi @mahmoudmy ! Thank you for the feedback.
I'm cleaning and improving a bit this plugin. Is this issue still true ?
I've just conducted some tests and in my case, it seems working just fine.
``` javascript
    ...
    var control = L.Control.fileLayerLoad(options).addTo(map);
    setTimeout(function () {
        control.removeFrom(map);
    }, 2000);
```
Could you please confirm ?

**Comment by mahmoudmy** [comment]
Hi @SBats , Thanks.
Yes, it's OK!

**Comment by SBats** [comment]
Ok great ! Thanks for answering !
