### ISSUE TITLE
leaflet 1.0

### ISSUE THREAD

**Issue by gornak49** [makinacorpus/Leaflet.FileLayer#35]
Will the FileLayer plugin work with leaflet 1.0?

**Comment by SBats** [comment]
Hi @gornak49 , thank you for reaching out.
At the moment, FileLayer is not compatible with Leaflet 1.
We don't know yet when we will be able to work on it.
In  the meantime, if you are willing to help, you could start a PR and we could help you working on it :+1:

**Comment by SBats** [comment]
Fixed, please see #46.
