### ISSUE TITLE
Cannot read property 'editing' of undefined

### ISSUE THREAD

**Issue by ldoloscan** [makinacorpus/Leaflet.FileLayer#43]
Hello,
I'm getting an error when i try to load file second time
`Cannot read property 'editing' of undefined`

What could it possibly be ?

**Comment by ldoloscan** [comment]
Sorry, my bad, i've done something wrong.
Btw, is it possible to get latlngs from imported .kml ?

Thanks.

**Comment by SBats** [comment]
Hi, you can access all the imported layers properties through the event.layer properties in the loaded event. Please see an updated example in the README -> Usage -> Events part.
