### ISSUE TITLE
Not running with Leaflet v1.1.0

### ISSUE THREAD

**Issue by ppete2** [makinacorpus/Leaflet.FileLayer#46]
This plugin is not running with new Leaflet v1.1.0
Besides some warning on the JS-console it creates a **_Type Error "L.Util.fileLoader is not a function"_**

Would be great if somebody is able to fix it.

**Comment by leplatrem** [comment]
@thorinii submitted a patch in #45. Now waiting for makinacorpus to merge and release. In the meantine you can use his branch:

https://cdn.rawgit.com/thorinii/Leaflet.FileLayer/588d5a401e63e386b4d929a488ce2569c0619cda/src/leaflet.filelayer.js

**Comment by SBats** [comment]
The npm version has been updated thanks to @thorinii fix on #45!

**Comment by okvittem** [comment]
Current leaflet-filelayer@1.2.0  does not install L.Control.fileLayerLoad function.
Whereas 0.4.0 works as expected but logs message "Deprecated include of L.Mixin.Events".
Tried with different leaflet from 1.0.0 to 1.4.3.
