### ISSUE TITLE
Inherit from L.Evented instead of L.Mixin.Events for custom events

### ISSUE THREAD

**Issue by SBats** [makinacorpus/Leaflet.FileLayer#47]
As stated in console `L.Mixin.Events` is now deprecated and will be removed and any custom event should instead inherit from `L.Evented`.

**Comment by ldoloscan** [comment]
The same here,
any workaround to get rid of this WARNING ?

**Comment by SBats** [comment]
The plugin needs to be updated. I don't think it's a lot of work if you want to try a PR :).
Otherwise, I'll try to give it a look but I have no idea when I'll find time for this.

**Comment by ppete2** [comment]
Bug here too with Leaflet v1.2

**Comment by SBats** [comment]
Fixed with the release 1.2.0! #51
