### ISSUE TITLE
How to use the points which come from the leaflet file layer plugin?

### ISSUE THREAD

**Issue by academicgirl** [makinacorpus/Leaflet.FileLayer#48]
How to use the points which come from the leaflet file layer plugin?

I am using leaflet file layer plugin.I have added a kml file which includes some points. I want to do sth by using these points. But I don't know if the plugin saves this data or not. How can I use these points?

**Comment by leplatrem** [comment]
```js
control.loader.on('data:loaded', function (e) {
    const layer = e.layer;
    // Do something here with the layer, like introspect its points.
    // See Leaflet.js reference.
});
```

**Comment by SBats** [comment]
Thanks @leplatrem for giving example! I've added one as well in the dev folder code.
