### ISSUE TITLE
release 1.0.0 or 1.1.0?

### ISSUE THREAD

**Issue by kkdd** [makinacorpus/Leaflet.FileLayer#50]
Hello,

In https://github.com/makinacorpus/Leaflet.FileLayer,
> Changelog
> 1.0.0
> Leaflet 1.1.0 compatibility (thanks @thorinii)

but in https://github.com/makinacorpus/Leaflet.FileLayer/releases
> Latest release
> 1.1.0
> @SBats SBats released this on 4 Aug · 3 commits to master since this release
> Fixes
> Leaflet 1.1.0 compatibility 🎉 (Fix #45 and #46) Thanks to @thorinii!

**Comment by SBats** [comment]
That was indeed a mistake. I should have published a 1.0.0 :/
I'll publish a new release to correct this and take your fix into account this weekend.

**Comment by SBats** [comment]
Version 1.2.0 released!
