### ISSUE TITLE
 L.Control.fileLayerLoad is not a function 

### ISSUE THREAD

**Issue by mladenp** [makinacorpus/Leaflet.FileLayer#73]
I am getting this error when i use it with create-react-app:
`TypeError: leaflet__WEBPACK_IMPORTED_MODULE_3___default.a.Control.fileLayerLoad is not a function`
I tried different togeojson packages but it doesn't make any difference.

**Comment by leplatrem** [comment]
Honestly I don't know how to help here...

**Comment by mladenp** [comment]
I found different package that solved my issue, i couldn't get this one to load in CRA even when manually adding togeojson.

**Comment by Ricardogh** [comment]
alguien me puede colaborar por favor con este error leaflet__WEBPACK_IMPORTED_MODULE_3___default.a.Control.fileLayerLoad is not a function, estoy utilizando angular 15
