### ISSUE TITLE
Ability to upload zipped shapefile

### ISSUE THREAD

**Issue by melanievt** [makinacorpus/Leaflet.FileLayer#96]
Hi,
Thank you very much for sharing such a great tool🙏🏽 I'm wondering if it is possible to revise it so that it accepts zipped shapefiles as inputs in addition to GeoJSON, JSON, GPX and KML.
Thanks in advance,
Mel

**Comment by camillemonchicourt** [comment]
If we should add the support for GIS files, I would rather choose an opensource and stronger format such as Geopackage (.gpkg).
But we initially choose to focus on format easy to manage server side, and thought it was easy to convert a shapefile or Geopackage file into Geojson with softwares such as QGIS.

**Comment by camillemonchicourt** [comment]
Duplicate https://github.com/makinacorpus/Leaflet.FileLayer/issues/7

**Comment by melanievt** [comment]
Thank you very much for the information @camillemonchicourt🙏🏽I had a look at the existing issues before opening mine, yet I missed the second page. Apologise for the duplication.
